# 11 Perform vectorized implementation of simple matrix operation like finding the transpose of a matrix, adding, subtracting or multiplying two matrices.

In [1]:
import numpy as np
A = np.array([[3, 6, 9], [5, -10, 15], [-7, 14, 21]])
B = np.array([[9, -18, 27], [11, 22, 33], [13, -26, 39]])
print("A = \n", A, "\nB = \n", B)

A = 
 [[  3   6   9]
 [  5 -10  15]
 [ -7  14  21]] 
B = 
 [[  9 -18  27]
 [ 11  22  33]
 [ 13 -26  39]]


In [2]:
# Addition
A + B

array([[ 12, -12,  36],
       [ 16,  12,  48],
       [  6, -12,  60]])

In [3]:
# Subtraction
A - B

array([[ -6,  24, -18],
       [ -6, -32, -18],
       [-20,  40, -18]])

In [4]:
# Multiplication
A @ B

array([[ 210, -156,  630],
       [ 130, -700,  390],
       [ 364, -112, 1092]])

In [5]:
# Transpose
print("A' = \n", np.transpose(A),
"\nB' = \n", np.transpose(B))

A' = 
 [[  3   5  -7]
 [  6 -10  14]
 [  9  15  21]] 
B' = 
 [[  9  11  13]
 [-18  22 -26]
 [ 27  33  39]]
