# 4 Create/Define single dimension / multidimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

In [1]:
import numpy as np

In [2]:
# Creating single-dimension arrays
x = np.array([1, 2, 3, 4, 5])
print('x = ', x)
y = np.array([[1], [2], [3]])
print('y = \n', y)

x =  [1 2 3 4 5]
y = 
 [[1]
 [2]
 [3]]


In [3]:
# Creating multi-dimension arrays
z = np.array([[1, 2, 3], [6, 7, 8]])
print('z = \n', z)
z1 = np.matrix('1 2 3; 6 7 8')
print('z1 = \n', z1)

z = 
 [[1 2 3]
 [6 7 8]]
z1 = 
 [[1 2 3]
 [6 7 8]]


In [4]:
# Matrix with all ones
A = np.ones((4, 4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Matrix with all zeros
B = np.zeros((4, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# Matrix with random values within a range
C = np.random.randint(20, 50, (4,5))
print("C = \n", C)
# Matrix with range
C1 = np.arange(12).reshape((3, 4))
print("C1 = \n", C1)

C = 
 [[24 43 21 36 22]
 [40 31 32 41 47]
 [46 22 27 46 47]
 [44 27 20 28 26]]
C1 = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# Diagonal matrix
D = np.diag([1, 2, 3, 4, 5])
print('D = \n', D)

D = 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
