# 6 Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix.

In [1]:
import numpy as np
A = np.array([[3, 6, 9], [5, -10, 15], [-7, 14, 21]])
B = np.array([[9, -18, 27], [11, 22, 33], [13, -26, 39]])
print("A = \n", A, "\nB = \n", B)

A = 
 [[  3   6   9]
 [  5 -10  15]
 [ -7  14  21]] 
B = 
 [[  9 -18  27]
 [ 11  22  33]
 [ 13 -26  39]]


In [2]:
# Matrix Addition
C = A + B
print('C = A + B =\n', C)

C = A + B =
 [[ 12 -12  36]
 [ 16  12  48]
 [  6 -12  60]]


In [3]:
# Matrix Subtraction
C = A - B
print('C = A - B =\n', C)

C = A - B =
 [[ -6  24 -18]
 [ -6 -32 -18]
 [-20  40 -18]]


In [4]:
# Matrix Multiplication
C = A.dot(B)
print('C = A * B =\n', C)

C = A * B =
 [[ 210 -156  630]
 [ 130 -700  390]
 [ 364 -112 1092]]


In [5]:
# Print 2nd row of Matrix A
print(A[1:2])

[[  5 -10  15]]


In [6]:
# Print 1st row of Matrix B
print(B[:1])

[[  9 -18  27]]


In [7]:
# Print 2nd column of Matrix A
print(A[:,1:2])

[[  6]
 [-10]
 [ 14]]


In [8]:
# Print 3rd column of Matrix B
print(B[:,2:3])

[[27]
 [33]
 [39]]
