# 7 Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix.

In [1]:
import numpy as np
A = np.array([[3, 6, 9], [5, -10, 15], [-7, 14, 21]])
B = np.array([[9, -18, 27], [11, 22, 33], [13, -26, 39]])
print("A = \n", A, "\nB = \n", B)

A = 
 [[  3   6   9]
 [  5 -10  15]
 [ -7  14  21]] 
B = 
 [[  9 -18  27]
 [ 11  22  33]
 [ 13 -26  39]]


In [2]:
# Converting matrix A data to its absolute values
np.absolute(A)

array([[ 3,  6,  9],
       [ 5, 10, 15],
       [ 7, 14, 21]])

In [3]:
# Converting matrix B data to its negative values
np.negative(B)

array([[ -9,  18, -27],
       [-11, -22, -33],
       [-13,  26, -39]])

In [4]:
# Deleting a row from Matrix A
np.delete(A, 1, 0)

array([[ 3,  6,  9],
       [-7, 14, 21]])

In [5]:
# Deleting a column from Matrix B
np.delete(B, 0, 1)

array([[-18,  27],
       [ 22,  33],
       [-26,  39]])

In [6]:
# Adding a row to Matrix A
np.append(A, np.array([[23, -45, 56]]), axis=0)

array([[  3,   6,   9],
       [  5, -10,  15],
       [ -7,  14,  21],
       [ 23, -45,  56]])

In [7]:
# Adding a column to Matrix B
np.append(B, [[23], [-45], [56]], axis=1)

array([[  9, -18,  27,  23],
       [ 11,  22,  33, -45],
       [ 13, -26,  39,  56]])

In [8]:
# Maximum of 2nd row of Matrix A
np.max(A, 0)[1]

14

In [9]:
# Maximum of 3rd column of Matrix B
np.max(B, 1)[2]

39

In [10]:
# Minimum of 3rd column of Matrix B
np.min(B, 1)[2]

-26

In [11]:
# Sum of some elements of array
np.sum(A[1:, 1:])

40

In [12]:
# Sum of all elements of array
sumA = np.sum(A)
sumB = np.sum(B)
print('sumA = ', sumA, ', sumB = ', sumB)

sumA =  56 , sumB =  110
